### ISSUE TITLE
Error running redux docker 

### ISSUE THREAD

**Issue by stevenroose** [movim/movim_docker#10]
```
movim_1          | 2018-06-21T15:23:11.418548000Z Movim not found in /var/www/html - copying now...
movim_1          | 2018-06-21T15:23:12.215160000Z Complete! Movim 0.13 has been successfully copied to /var/www/html
movim_1          | 2018-06-21T15:23:12.603617000Z Oops... something went wrong.
movim_1          | 2018-06-21T15:23:12.604025000Z Uncaught Error: Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /var/www/html/vendor/movim/modl/src/Modl/Modl.php:134
movim_1          | 2018-06-21T15:23:12.604312000Z Stack trace:
movim_1          | 2018-06-21T15:23:12.604619000Z #0 /var/www/html/src/Movim/Bootstrap.php(302): Modl\Modl->connect()
movim_1          | 2018-06-21T15:23:12.604896000Z #1 /var/www/html/src/Movim/Bootstrap.php(27): Movim\Bootstrap->loadModl()
movim_1          | 2018-06-21T15:23:12.605220000Z #2 /var/www/html/mud.php(14): Movim\Bootstrap->boot()
movim_1          | 2018-06-21T15:23:12.605515000Z #3 {main}
movim_1          | 2018-06-21T15:23:12.605792000Z   thrown
movim_1          | 2018-06-21T15:23:12.606085000Z in /var/www/html/vendor/movim/modl/src/Modl/Modl.php (line 134)
movim_1          | 2018-06-21T15:23:12.671163000Z konuro_movim_1 exited with code 255
```

**Comment by kawaii** [comment]
I believe this happens because the redux `Dockerfile` doesn't contain the MySQL extension for PHP, only the PostgreSQL extension. You should use a PostgreSQL database container instead since I don't really want to encourage the use of MySQL. :slightly_smiling_face:

https://hub.docker.com/_/postgres/

**Comment by stevenroose** [comment]
@kawaii, what's wrong with MySQL? I use MariaDB, fwiw.

**Comment by kawaii** [comment]
@stevenroose read this, it applies to both MariaDB and MySQL.

https://grimoire.ca/mysql/choose-something-else
